# Creating Ndarrays in NumPy

In [33]:
import numpy as np

In [34]:
my_list = list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [36]:
array_1 = np.array(my_list)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
print(array_1)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
multi_list = [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
multi_list

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]

In [39]:
array_2 = np.array(multi_list)
array_2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [40]:
print(array_2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
array_1.ndim

1

In [42]:
array_2.ndim

2

In [43]:
array_2.shape

(2, 6)

In [44]:
multi_2x3 = [[[1,2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]
multi_2x3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [45]:
array_multi_2x3 = np.array(multi_2x3)
array_multi_2x3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [46]:
array_multi_2x3.ndim

3

In [47]:
array_multi_2x3.shape

(3, 2, 2)

In [48]:
multi_3x3 = [[[1,2, 0], [3, 4, 0]], [[5, 6, 0], [7, 8, 0]], [[9, 10, 0], [11, 12, 0]]]
multi_3x3

[[[1, 2, 0], [3, 4, 0]], [[5, 6, 0], [7, 8, 0]], [[9, 10, 0], [11, 12, 0]]]

In [49]:
array_multi_3x3 = np.array(multi_3x3)
array_multi_3x3

array([[[ 1,  2,  0],
        [ 3,  4,  0]],

       [[ 5,  6,  0],
        [ 7,  8,  0]],

       [[ 9, 10,  0],
        [11, 12,  0]]])

In [50]:
print(array_multi_3x3.ndim)
print(array_multi_3x3.shape)

3
(3, 2, 3)


In [51]:
print(array_2.dtype)

int32


In [52]:
print(array_1.dtype)

int32


In [53]:
my_list2 = [1, 2, 3, 4, 5, 6.5, 7, 8, 9]
my_list2

[1, 2, 3, 4, 5, 6.5, 7, 8, 9]

In [54]:
array_3 = np.array(my_list2)
array_3

array([1. , 2. , 3. , 4. , 5. , 6.5, 7. , 8. , 9. ])

In [55]:
print(array_3.dtype)

float64


In [56]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
zeros_ndarray = np.zeros((3, 6))
zeros_ndarray

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [58]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
empty_array = np.empty((3, 3, 2))
empty_array

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [60]:
array_arange = np.arange(20)
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [63]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])